name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      # Step 2: Set up SSH for EC2 access
      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          eval $(ssh-agent -s)
          ssh-add /tmp/ssh_key

      # Step 3: SSH into EC2 and deploy
      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -i /tmp/ssh_key ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # Exit on any error

            cd /home/ubuntu/open-webui || { echo "Directory not found"; exit 1; }

            echo "🔄 Resetting and pulling latest code..."
            git reset --hard HEAD
            git pull origin main || { echo "Git pull failed"; exit 1; }

            echo "🔨 Building Docker images..."
            docker-compose build --no-cache || { echo "Docker build failed"; exit 1; }

            echo "🛑 Stopping old container gracefully..."
            docker-compose down || echo "No running container to stop"

            echo "🚀 Starting new container..."
            docker-compose up -d --remove-orphans || { echo "Docker up failed"; exit 1; }

            echo "📦 Checking logs for confirmation..."
            docker logs --tail=100 open-webui || echo "Unable to fetch logs"

            echo "✅ Deployment finished successfully."
          EOF
